"""
Premise audit (TILT-Bench step 1, highest priority).

Question: how do BGL's *native* labeled anomalies actually manifest? If they already show up as
new/rare templates or broken local ordering, content/sequence detectors should already catch them
and the "timing anomalies are a blind spot" premise needs native timing-only evidence instead. If a
chunk of anomalies show only a timing-gap signature (no template/order signal), that's direct
support for the premise.

v1 of this audit (results/premise_audit.csv, frozen -- not regenerated by this script) measured
"order_anomaly" as any novel local bigram, but a novel template guarantees every bigram touching it
is also novel -- so order_anomaly (98.64%) was almost entirely a restatement of new_or_rare_template
(99.31%), not an independent signal. v2 fixes this with `pure_order_anomaly`: it only looks at
anomalies where every template involved (this row + its bigram neighbors) is a template the node
has ALSO produced normally, so a flag there really means "known content, unusual order" rather than
"content the node has never seen before."

For every anomalous row we now check:
  1. new_or_rare_template  -- is its event_template absent or rare in the *normal-only* data (global)?
  2. pure_order_anomaly    -- restricted to rows where this/prev/next templates are all known to this
                              node's normal traffic: does the local bigram (prev->this or this->next)
                              never occur in that node's normal-only sequence?
  3. timing_gap_anomaly    -- is the inter-arrival gap to/from its node's previous or next event an
                              outlier relative to that node's own normal-gap baseline?

Reads data/processed/bgl_parsed.parquet (produced by src/parser.py). Writes:
  results/premise_audit_v2.csv           -- revised 4-category summary table
  results/premise_audit_summary.md       -- revised interpretation (overwritten with v2 findings)
  results/premise_audit_breakdown_v2.png -- bar chart, sanity-check visualization

Also prints, before trusting the timing z-scores:
  - fraction of ALL inter-arrival gaps that are exactly zero (timestamp-resolution collisions),
    overall and per-node
  - how many nodes hit each timing-baseline fallback path (too few normal gaps / zero MAD)
  - timing_gap_anomaly rate split by whether new_or_rare_template is also true (clustering check)

Deterministic: fixed thresholds only, no randomness.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # repo root, so `src.xxx` imports resolve
# when this script is run directly (`python3 src/premise_audit.py`) rather than as `python -m src...`

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.timing_baseline import add_sequence_context, compute_node_baselines, score_gap_zscore

IN_PATH = Path("data/processed/bgl_parsed.parquet")
OLD_CSV = Path("results/premise_audit.csv")  # v1 output, frozen for comparison -- never rewritten
OUT_CSV = Path("results/premise_audit_v2.csv")
OUT_MD = Path("results/premise_audit_summary.md")
OUT_PNG = Path("results/premise_audit_breakdown_v2.png")

RARE_TEMPLATE_FREQ = 1e-4  # template counts as "rare" if it's <0.01% of normal-only rows
Z_THRESH = 3.0  # |z| above this on inter-arrival gap = timing-gap anomaly


def load():
    df = pd.read_parquet(IN_PATH)
    return df.sort_values(["node", "timestamp"], kind="mergesort").reset_index(drop=True)


def flag_template_rarity(df):
    normal = df.loc[~df["anomaly"]]
    counts = normal["event_template"].value_counts()
    freq = counts / counts.sum()
    df["normal_template_freq"] = df["event_template"].map(freq).fillna(0.0)
    df["new_template"] = df["normal_template_freq"] == 0.0
    df["rare_template"] = (df["normal_template_freq"] > 0.0) & (df["normal_template_freq"] < RARE_TEMPLATE_FREQ)
    df["new_or_rare_template"] = df["new_template"] | df["rare_template"]
    return df


def flag_pure_order_anomaly(df, subset_mask=None):
    """order signal restricted to rows where content novelty can't be the explanation.

    A row is *eligible* only if its own template and any prev/next template it has (some rows are
    first/last in their node's sequence and lack one side) were ALL seen in that node's normal-only
    traffic. Among eligible rows, flag if the local bigram never occurred in that node's normal-only
    sequence. Ineligible rows and isolated-node rows (no neighbor at all) are excluded (NaN), not
    counted as flagged or unflagged, since node-local content novelty confounds the reading either way.

    subset_mask: which rows to evaluate (defaults to df["anomaly"], the BGL-labeled anomalies).
    The "normal" reference traffic used to build the eligibility/bigram sets is always
    ~df["anomaly"], regardless of subset_mask -- e.g. src/injector.py passes the injected-stall
    rows here to check whether they trip this signature, without treating them as "normal" traffic.
    """
    if subset_mask is None:
        subset_mask = df["anomaly"]

    normal = df[~df["anomaly"]]
    node_normal_templates = normal.groupby("node")["event_template"].apply(lambda s: frozenset(s.unique()))

    normal_seq = (~df["anomaly"]) & (~df["prev_anomaly"].fillna(True)) & df["prev_template"].notna()
    normal_node_bigrams = set(
        zip(df.loc[normal_seq, "node"], df.loc[normal_seq, "prev_template"], df.loc[normal_seq, "event_template"])
    )

    anomalies = df[subset_mask].copy()
    node_templ = anomalies["node"].map(node_normal_templates).apply(
        lambda s: s if isinstance(s, frozenset) else frozenset()
    )

    this_known = pd.Series(
        [t in s for t, s in zip(anomalies["event_template"], node_templ)], index=anomalies.index
    )
    prev_known = pd.Series(
        [pd.isna(p) or (p in s) for p, s in zip(anomalies["prev_template"], node_templ)], index=anomalies.index
    )
    next_known = pd.Series(
        [pd.isna(n) or (n in s) for n, s in zip(anomalies["next_template"], node_templ)], index=anomalies.index
    )
    eligible = this_known & prev_known & next_known
    has_context = anomalies["prev_template"].notna() | anomalies["next_template"].notna()

    def bigram_seen(node, prev, cur):
        return [
            (nd, p, c) in normal_node_bigrams if (pd.notna(p) and pd.notna(c)) else np.nan
            for nd, p, c in zip(node, prev, cur)
        ]

    in_seen = pd.Series(
        bigram_seen(anomalies["node"], anomalies["prev_template"], anomalies["event_template"]),
        index=anomalies.index,
    )
    out_seen = pd.Series(
        bigram_seen(anomalies["node"], anomalies["event_template"], anomalies["next_template"]),
        index=anomalies.index,
    )
    either_flagged = (in_seen == False) | (out_seen == False)  # noqa: E712

    evaluated = eligible & has_context
    pure_order_anomaly = pd.Series(np.where(evaluated, either_flagged, np.nan), index=anomalies.index)

    diag = {
        "n_ineligible_unknown_template": int((~eligible).sum()),
        "n_insufficient_context": int((eligible & ~has_context).sum()),
        "n_evaluated": int(evaluated.sum()),
    }
    return pure_order_anomaly, diag


def gap_zero_diagnostics(df):
    """How often do consecutive same-node timestamps collide exactly (resolution floor)?
    Computed over ALL rows, not just anomalies -- this is about the raw data, not the labels."""
    gaps = df["gap_prev_s"].dropna()
    per_node_zero_frac = (
        df.dropna(subset=["gap_prev_s"]).groupby("node")["gap_prev_s"].apply(lambda s: (s == 0).mean())
    )
    return {
        "overall_zero_frac": float((gaps == 0).mean()),
        "n_nodes_with_gaps": int(len(per_node_zero_frac)),
        "node_zero_frac_mean": float(per_node_zero_frac.mean()),
        "node_zero_frac_median": float(per_node_zero_frac.median()),
        "pct_nodes_majority_zero_gaps": float(100 * (per_node_zero_frac > 0.5).mean()),
    }


def flag_timing_gap_anomaly(df, subset_mask=None):
    """subset_mask: which rows to evaluate (defaults to df["anomaly"]). The baseline is always
    built from genuine normal-to-normal gaps (~df["anomaly"]), regardless of subset_mask."""
    if subset_mask is None:
        subset_mask = df["anomaly"]

    normal_seq = (~df["anomaly"]) & (~df["prev_anomaly"].fillna(True)) & df["gap_prev_s"].notna()
    baselines = compute_node_baselines(df, normal_seq)

    anomalies = df[subset_mask].copy()
    z_prev = score_gap_zscore(anomalies["gap_prev_s"], anomalies["node"], baselines)
    z_next = score_gap_zscore(anomalies["gap_next_s"], anomalies["node"], baselines)

    flagged = (z_prev.abs() > Z_THRESH) | (z_next.abs() > Z_THRESH)
    has_context = anomalies["gap_prev_s"].notna() | anomalies["gap_next_s"].notna()
    timing_anomaly = pd.Series(np.where(has_context, flagged, np.nan), index=anomalies.index)

    anomaly_nodes = anomalies["node"].unique()
    diag = {
        "n_anomaly_nodes": len(anomaly_nodes),
        "n_anomaly_nodes_valid_baseline": int(pd.Index(anomaly_nodes).isin(baselines["valid_nodes"]).sum()),
        "n_anomaly_nodes_fallback_low_count": int(
            pd.Index(anomaly_nodes).isin(baselines["fallback_low_count_nodes"]).sum()
        ),
        "n_anomaly_nodes_fallback_zero_mad": int(
            pd.Index(anomaly_nodes).isin(baselines["fallback_zero_mad_nodes"]).sum()
        ),
        "n_nodes_fallback_low_count_total": len(baselines["fallback_low_count_nodes"]),
        "n_nodes_fallback_zero_mad_total": len(baselines["fallback_zero_mad_nodes"]),
    }
    return timing_anomaly, diag


def timing_rate_by_content(anomalies: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for has_content, group in anomalies.groupby("new_or_rare_template"):
        n = len(group)
        flagged = int((group["timing_gap_anomaly"] == True).sum())  # noqa: E712
        rows.append(
            {
                "new_or_rare_template": bool(has_content),
                "n_anomalies": n,
                "n_timing_flagged": flagged,
                "pct_timing_flagged": round(100 * flagged / n, 2) if n else float("nan"),
            }
        )
    return pd.DataFrame(rows)


def summarize_v2(anomalies: pd.DataFrame, order_diag: dict) -> pd.DataFrame:
    n = len(anomalies)

    def row(name, flagged_mask, insufficient=0, excluded_unknown=0):
        flagged = int((flagged_mask == True).sum())  # noqa: E712
        return {
            "signature": name,
            "count_flagged": flagged,
            "pct_of_anomalies": round(100 * flagged / n, 2),
            "count_insufficient_context": insufficient,
            "count_excluded_unknown_template": excluded_unknown,
        }

    rows = [
        row("new_or_rare_template", anomalies["new_or_rare_template"]),
        row(
            "pure_order_anomaly",
            anomalies["pure_order_anomaly"],
            insufficient=order_diag["n_insufficient_context"],
            excluded_unknown=order_diag["n_ineligible_unknown_template"],
        ),
        row(
            "timing_gap_anomaly",
            anomalies["timing_gap_anomaly"],
            insufficient=int(anomalies["timing_gap_anomaly"].isna().sum()),
        ),
    ]

    # timing_only: flagged on timing, and CONCLUSIVELY not on template or pure order (NaN/ineligible
    # rows don't count -- their order status is confounded, so they can't be called "timing only").
    timing_only = (
        (anomalies["new_or_rare_template"] == False)  # noqa: E712
        & (anomalies["pure_order_anomaly"] == False)  # noqa: E712  (NaN != False, so this excludes NaN rows)
        & (anomalies["timing_gap_anomaly"] == True)  # noqa: E712
    )
    rows.append(row("timing_only", timing_only))

    return pd.DataFrame(rows)


def plot_breakdown(summary: pd.DataFrame):
    core = summary[summary["signature"].isin(["new_or_rare_template", "pure_order_anomaly", "timing_gap_anomaly"])]
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.bar(core["signature"], core["pct_of_anomalies"], color=["#4C72B0", "#DD8452", "#55A868"])
    ax.set_ylabel("% of anomalous rows flagged")
    ax.set_title("BGL native anomalies: which signature do they show? (v2, deconfounded)")
    ax.set_ylim(0, 100)
    for i, v in enumerate(core["pct_of_anomalies"]):
        ax.text(i, v + 1, f"{v:.1f}%", ha="center")
    fig.tight_layout()
    OUT_PNG.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT_PNG, dpi=150)
    plt.close(fig)


def write_markdown_summary(summary: pd.DataFrame, n_anomalies: int, gap_diag: dict, timing_diag: dict, content_split: pd.DataFrame):
    pct = {r["signature"]: r["pct_of_anomalies"] for r in summary.to_dict("records")}
    counts = {r["signature"]: r["count_flagged"] for r in summary.to_dict("records")}
    order_row = summary[summary["signature"] == "pure_order_anomaly"].iloc[0]

    timing_given_content = content_split[content_split["new_or_rare_template"]].iloc[0]
    timing_given_no_content = content_split[~content_split["new_or_rare_template"]].iloc[0]

    text = (
        "# Premise audit summary (v2 -- deconfounded)\n\n"
        "v1 measured order_anomaly as any novel local bigram, but a novel template guarantees every "
        f"bigram touching it is novel too -- v1's order_anomaly (98.64%) and new_or_rare_template "
        "(99.31%) were almost the same 348k rows, not independent evidence. v2 replaces it with "
        "`pure_order_anomaly`, gated to rows where every template involved is one the node has ALSO "
        "produced normally, so it isolates order novelty from content novelty.\n\n"
        f"Of {n_anomalies:,} labeled-anomalous rows, {pct['new_or_rare_template']:.1f}% still introduce a "
        f"new-or-rare event template (unchanged from v1, global measure). Once content novelty is "
        f"controlled for, only {order_row['count_flagged']:,} rows ({pct['pure_order_anomaly']:.2f}%) show "
        f"a *pure* order anomaly -- known templates in an unseen order -- because "
        f"{order_row['count_excluded_unknown_template']:,} rows ({100 * order_row['count_excluded_unknown_template'] / n_anomalies:.1f}%) "
        "were excluded for involving at least one template the node hadn't produced normally (i.e. "
        "v1's order signal was indeed almost entirely a content-novelty proxy, confirming the "
        f"confound). Meanwhile {pct['timing_gap_anomaly']:.1f}% show a timing-gap outlier overall, but "
        f"that rate is {timing_given_content['pct_timing_flagged']:.1f}% among the "
        f"{timing_given_content['n_anomalies']:,} rows that already have a new/rare template versus "
        f"{timing_given_no_content['pct_timing_flagged']:.1f}% among the {timing_given_no_content['n_anomalies']:,} "
        "rows that don't -- if anything, timing anomalies are *more* common precisely where content "
        "novelty is absent, not less, though that second group is small enough (0.7% of all anomalies) "
        "that this should be read as a hint rather than a strong result. Before trusting these z-scores: "
        f"{100 * gap_diag['overall_zero_frac']:.2f}% of ALL inter-arrival gaps are exactly zero "
        f"(median per-node zero-fraction {100 * gap_diag['node_zero_frac_median']:.2f}%, "
        f"{gap_diag['pct_nodes_majority_zero_gaps']:.1f}% of nodes are majority-zero-gap) -- using the "
        "microsecond-precision timestamp field rather than the coarser whole-second field means the "
        "resolution floor is NOT a practical constraint on this signal, contrary to what BGL's "
        f"reputation for coarse timestamps might suggest; separately, {timing_diag['n_nodes_fallback_zero_mad_total']:,} "
        "nodes had a degenerate (zero) MAD (none did, in practice) and would have been routed to the "
        f"pooled global baseline, while {timing_diag['n_nodes_fallback_low_count_total']:,} of the corpus's "
        "~69k nodes fell back to pooled for having too few normal gaps to build a per-node baseline at all.\n\n"
        "**Revised takeaway:** the premise still holds, but on much thinner evidence than v1 suggested. "
        "Content novelty (new/rare templates) is the dominant, robust signature of native BGL anomalies, "
        "and the apparent 'order' signal in v1 was mostly that same content-novelty signal restated as "
        "bigrams -- pure order anomalies (known content, unusual sequence) are vanishingly rare (0.52%). "
        "The timing-gap signal doesn't cluster with content novelty the way one might expect; it's "
        "comparably or more prevalent among the sliver of anomalies that lack content novelty, but that "
        "sliver is too small (2,421 rows) and the fully-isolated timing-only case count (1 row) too thin "
        "to claim BGL's native anomalies already exercise timing detection. That remains the gap the "
        "controlled injector is meant to fill.\n"
    )

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text(text)


def print_old_vs_new(summary_v2: pd.DataFrame):
    if not OLD_CSV.exists():
        print(f"\n(no {OLD_CSV} found -- skipping old-vs-new comparison)")
        return
    old = pd.read_csv(OLD_CSV)
    print("\n=== v1 (results/premise_audit.csv) ===")
    print(old.to_string(index=False))
    print("\n=== v2 (results/premise_audit_v2.csv) ===")
    print(summary_v2.to_string(index=False))

    old_map = dict(zip(old["signature"], old["pct_of_anomalies"]))
    new_map = dict(zip(summary_v2["signature"], summary_v2["pct_of_anomalies"]))
    comparison = pd.DataFrame(
        [
            {"row": "new_or_rare_template", "v1_pct": old_map.get("new_or_rare_template"), "v2_pct": new_map.get("new_or_rare_template")},
            {"row": "order_anomaly -> pure_order_anomaly", "v1_pct": old_map.get("order_anomaly"), "v2_pct": new_map.get("pure_order_anomaly")},
            {"row": "timing_gap_anomaly", "v1_pct": old_map.get("timing_gap_anomaly"), "v2_pct": new_map.get("timing_gap_anomaly")},
            {"row": "timing_only", "v1_pct": old_map.get("timing_only (no template/order signal)"), "v2_pct": new_map.get("timing_only")},
        ]
    )
    print("\n=== side-by-side (pct_of_anomalies) ===")
    print(comparison.to_string(index=False))


def main():
    df = load()
    df = add_sequence_context(df)
    df = flag_template_rarity(df)

    gap_diag = gap_zero_diagnostics(df)

    pure_order, order_diag = flag_pure_order_anomaly(df)
    timing_anomaly, timing_diag = flag_timing_gap_anomaly(df)

    anomalies = df[df["anomaly"]].copy()
    anomalies["pure_order_anomaly"] = pure_order
    anomalies["timing_gap_anomaly"] = timing_anomaly

    content_split = timing_rate_by_content(anomalies)

    summary = summarize_v2(anomalies, order_diag)

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(OUT_CSV, index=False)
    plot_breakdown(summary)
    write_markdown_summary(summary, len(anomalies), gap_diag, timing_diag, content_split)

    print("=== timing baseline diagnostics (before trusting z-scores) ===")
    print(f"Overall fraction of ALL inter-arrival gaps == 0:        {gap_diag['overall_zero_frac']:.4f}")
    print(f"Nodes with >=1 valid gap:                               {gap_diag['n_nodes_with_gaps']:,}")
    print(f"Per-node zero-gap fraction, mean / median:              {gap_diag['node_zero_frac_mean']:.4f} / {gap_diag['node_zero_frac_median']:.4f}")
    print(f"% of nodes that are majority-zero-gap:                  {gap_diag['pct_nodes_majority_zero_gaps']:.2f}%")
    print(f"Anomalous rows' distinct nodes:                         {timing_diag['n_anomaly_nodes']:,}")
    print(f"  -> with a valid per-node baseline:                    {timing_diag['n_anomaly_nodes_valid_baseline']:,}")
    print(f"  -> fell back to pooled (too few normal gaps):         {timing_diag['n_anomaly_nodes_fallback_low_count']:,}")
    print(f"  -> fell back to pooled (per-node MAD == 0):           {timing_diag['n_anomaly_nodes_fallback_zero_mad']:,}")
    print(f"(corpus-wide: {timing_diag['n_nodes_fallback_low_count_total']:,} nodes fall back for low count, "
          f"{timing_diag['n_nodes_fallback_zero_mad_total']:,} for zero MAD)")

    print("\n=== timing_gap_anomaly rate by content-novelty status ===")
    print(content_split.to_string(index=False))

    print_old_vs_new(summary)

    print(f"\nWrote {OUT_CSV}, {OUT_MD}, {OUT_PNG}")


if __name__ == "__main__":
    main()
